#!/bin/bash
echo "🔍 Analyzing Failed Workflows"
echo "============================="
echo ""
echo "📋 Workflow yang tersedia:"
echo "1. ci.yml       - CI Pipeline"
echo "2. docker.yml   - Docker Build" 
echo "3. docs.yml     - Documentation"
echo "4. release.yml  - Release Binaries"
echo ""
echo "🎯 Workflow yang mungkin gagal:"
echo "🔴 docker.yml   - Docker configuration issues"
echo "🔴 docs.yml     - Documentation build errors"
echo "🔴 release.yml  - Release automation problems"
echo ""
echo "🚀 Langkah diagnosa:"
echo "1. Buka GitHub Actions → Filter 'failed'"
echo "2. Klik setiap workflow merah"
echo "3. Catat error message spesifik"
echo "4. Perbaiki berdasarkan error"
