#!/bin/bash
echo "🐛 Debug Workflow yang Gagal"
echo "============================="

echo "📋 Workflow yang tersedia:"
echo "✅ ci.yml    - Testing & Build"
echo "✅ docker.yml - Docker Images" 
echo "✅ docs.yml   - Dokumentasi"
echo "✅ release.yml - Release Binaries"
echo ""
echo "🔴 Workflow yang gagal biasanya menunjukkan:"
echo "   - Error kompilasi Rust"
echo "   - Test yang fail"
echo "   - Dependency issues"
echo "   - Permission problems"
echo ""
echo "🎯 Solusi cepat:"
echo "1. Buka GitHub Actions → Klik workflow merah → Lihat error"
echo "2. Perbaiki error berdasarkan log"
echo "3. Commit & push perbaikan"
